[package]
name = "blas-array2"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
derive_builder = { version = "0.20" }
libc = { version = "0.2" }
blas-sys = { version = "0.7" }
ndarray = { version = "0.15.6" }
num-complex = { version = "0.4" }
